# Snapshot report for `test/error-message.js`

The actual snapshot is saved in `error-message.js.snap`.

Generated by [AVA](https://avajs.dev).

## Invalid #1
      1 | throw new Error()

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error()␊
        |       ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
    `

## Invalid #2
      1 | throw Error()

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw Error()␊
        |       ^^^^^^^ Pass a message to the `Error` constructor.␊
    `

## Invalid #3
      1 | throw new Error('')

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error('')␊
        |                 ^^ Error message should not be an empty string.␊
    `

## Invalid #4
      1 | throw new Error(``)

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error(``)␊
        |                 ^^ Error message should not be an empty string.␊
    `

## Invalid #5
      1 | const err = new Error();
      2 | throw err;

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const err = new Error();␊
        |             ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      2 | throw err;␊
    `

## Invalid #6
      1 | let err = 1;
      2 | err = new Error();
      3 | throw err;

> Snapshot 1

    `␊
    Error 1/1:␊
      1 | let err = 1;␊
    > 2 | err = new Error();␊
        |       ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      3 | throw err;␊
    `

## Invalid #7
      1 | let err = new Error();
      2 | err = 1;
      3 | throw err;

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | let err = new Error();␊
        |           ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      2 | err = 1;␊
      3 | throw err;␊
    `

## Invalid #8
      1 | const foo = new TypeError()

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const foo = new TypeError()␊
        |             ^^^^^^^^^^^^^^^ Pass a message to the `TypeError` constructor.␊
    `

## Invalid #9
      1 | const foo = new SyntaxError()

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const foo = new SyntaxError()␊
        |             ^^^^^^^^^^^^^^^^^ Pass a message to the `SyntaxError` constructor.␊
    `

## Invalid #10
      1 | const errorMessage = Object.freeze({errorMessage: 1}).errorMessage;
      2 | throw new Error(errorMessage)

> Snapshot 1

    `␊
    Error 1/1:␊
      1 | const errorMessage = Object.freeze({errorMessage: 1}).errorMessage;␊
    > 2 | throw new Error(errorMessage)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## Invalid #11
      1 | throw new Error([])

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([])␊
        |                 ^^ Error message should be a string.␊
    `

## Invalid #12
      1 | throw new Error([foo])

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([foo])␊
        |                 ^^^^^ Error message should be a string.␊
    `

## Invalid #13
      1 | throw new Error([0][0])

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([0][0])␊
        |                 ^^^^^^ Error message should be a string.␊
    `

## Invalid #14
      1 | throw new Error({})

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({})␊
        |                 ^^ Error message should be a string.␊
    `

## Invalid #15
      1 | throw new Error({foo})

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({foo})␊
        |                 ^^^^^ Error message should be a string.␊
    `

## Invalid #16
      1 | throw new Error({foo: 0}.foo)

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({foo: 0}.foo)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## Invalid #17
      1 | throw new Error(lineNumber=2)

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error(lineNumber=2)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## Invalid #18
      1 | const error = new RangeError;

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const error = new RangeError;␊
        |               ^^^^^^^^^^^^^^ Pass a message to the `RangeError` constructor.␊
    `
